[package]
name = "clock-server"
version = "0.4.0"
authors = ["Sigurd Holsen <sighol@gmail.com>"]
description = "Simple TCP app that checks that server and client have the same clock"

[dependencies]
chrono = "*"
clap = "*"
byteorder = "*"